// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	model "github.com/aaanger/ecommerce/internal/cart/model"
	mock "github.com/stretchr/testify/mock"
)

// ICartService is an autogenerated mock type for the ICartService type
type ICartService struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: userID, productID, quantity
func (_m *ICartService) AddProduct(userID int, productID int, quantity int) (*model.Cart, error) {
	ret := _m.Called(userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 *model.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (*model.Cart, error)); ok {
		return rf(userID, productID, quantity)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) *model.Cart); ok {
		r0 = rf(userID, productID, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(userID, productID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: userID, productID
func (_m *ICartService) DeleteProduct(userID int, productID int) (*model.Cart, error) {
	ret := _m.Called(userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 *model.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*model.Cart, error)); ok {
		return rf(userID, productID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *model.Cart); ok {
		r0 = rf(userID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCartByUserID provides a mock function with given fields: userID
func (_m *ICartService) GetCartByUserID(userID int) (*model.Cart, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartByUserID")
	}

	var r0 *model.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Cart, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Cart); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewICartService creates a new instance of ICartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICartService {
	mock := &ICartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
