version: "3.9"

services:
  ecommerce-app:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PSQL_HOST: db
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
      PSQL_DBNAME: ${PSQL_DBNAME}

  db:
    image: postgres
    container_name: e_postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DBNAME}
    ports:
      - "5435:5432"